### ISSUE TITLE
Missing feature

### ISSUE THREAD

**Issue by Skyman29** [Skyman29/M05_BretonCretenet#5]
I just noticed that train_test_split nor the main is returning more than 3 splits as mentionned in the picture

![image](https://user-images.githubusercontent.com/105222077/228827890-5ccc9943-e8c2-4211-a2b3-6e82862bfa62.png)

**Comment by Cretenet** [comment]
Yes, I coded train_test_split to only return one, so that we can call it as many times as we want to have more than 1 split! I think that it should be changed in the main. What do you think?

**Comment by Skyman29** [comment]
Ok, I understand.
No problem to add the feature in the main.
